### PR TITLE
Update T_02_arguments_to_metaclasses.rst

### PR DESCRIPTION
**Pull request by 2022WPJ**
This may be a typo

### CODE REVIEW

**Comment by wolph** [comment]
It is not a typo :)

**Comment by 2022WPJ** [comment]
The class `AddClassAttribute` is defined, but not being used.

**Comment by wolph** [comment]
The `WithAttribute` class is inheriting the `AddClassAttribute` :)

This example shows how `__init_subclass__` can be an alternative to metaclasses in some cases

**Comment by 2022WPJ** [comment]
I think the same thing, but current code is: `class WithAttribute(metaclass=AddClassAttributeMeta, a=1234)`:)

**Comment by wolph** [comment]
Ah, now I see what you mean. That won't work though, just try and run this:

```python
>>> class AddClassAttribute:
...     def __init_subclass__(cls, **kwargs):
...         super().__init_subclass__()
...
...         for k, v in kwargs.items():
...             setattr(cls, k, v)


>>> class WithAttribute(AddClassAttributeMeta, a=1234):
...     pass
```

**Pull request closed without merging**
